# version: '3.8'

services:
  mini_bdx:
    build:
      context: .
      dockerfile: Dockerfile
    image: open-duck-ros-jazzy:latest

    # exactly like --network host
    network_mode: host

    # exactly like --privileged
    privileged: true

    # grant access to all input devices (major 13) at runtime
    device_cgroup_rules:
      - 'c 13:* rmw'

    # mount the host’s /dev/input (so new joystick nodes appear automatically)
    # also mount any specific static devices you know you’ll need (e.g. /dev/ttyACM0)
    volumes:
      # - $HOME/bdx_ws:/bdx_ws                 # uncomment this if you want to use a dev workspace outside the container
      - /dev/input:/dev/input                # bind‐mount the entire input directory
      - /dev/ttyACM0:/dev/ttyACM0            # if /dev/ttyACM0 is already present at startup
      - /dev/i2c-1:/dev/i2c-1                # same for I²C bus

    # exactly like -it
    stdin_open: true
    tty: true

    entrypoint: ["/ros_entrypoint.sh"]
    command: ["bash"]
