# Dockerfile.pi02w

# 1) Use the Pi-OS image with Python 3.10 already installed
FROM dtcooper/raspberrypi-os:python3.10-bookworm
ENV DEBIAN_FRONTEND=noninteractive

# 2) Set your workdir
WORKDIR /app

# 3) Install only what you need at build time (incl. the distro lgpio package)
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      python3-venv \
      python3-pip \
      python3-empy \
      build-essential \
      nano \
      git \
 && rm -rf /var/lib/apt/lists/*

# 4) Create & activate your venv
RUN python3 -m venv /opt/venv \
 && /opt/venv/bin/pip install --upgrade pip \
 && /opt/venv/bin/pip install PyYAML \
#  && /opt/venv/bin/pip install empy \
 && /opt/venv/bin/pip install lark-parser

ENV VIRTUAL_ENV=/opt/venv
ENV PATH="$VIRTUAL_ENV/bin:${PATH}"

RUN /opt/venv/bin/pip install RPi.GPIO

# 5) Now pip works un-protected. Install your runtime package & lgpio
RUN git clone --branch upgrades https://github.com/jmachuca77/Open_Duck_Mini_Runtime \
 && cd Open_Duck_Mini_Runtime \
 && pip install -e . lgpio \
 && /opt/venv/bin/pip install PyYAML

RUN /opt/venv/bin/pip install empy \
 && /opt/venv/bin/pip install lark-parser

SHELL ["/bin/bash", "-c"]

COPY ./run.sh /app/run.sh
COPY ./inputrc /root/.inputrc
COPY ./bashrc.pi02w /root/.bashrc
COPY ./duck_config.json /root/duck_config.json

# 7) Entrypoint & default
COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
CMD ["bash"]
